name: Setup
description: Specific steps to install dependencies shared between actions
inputs:
  platform:
    required: true
  arch:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: yarn
        node-version: lts/*
    - name: Install linux dependencies
      if: inputs.platform == 'linux'
      shell: bash
      run: |
        sudo apt-get -y update
        sudo apt-get -y install make nodejs
        sudo snap install zig --classic --beta
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: nightly
    - name: Install MacOS dependencies
      if: inputs.platform == 'darwin'
      shell: bash
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install zig make
        ln -s /usr/local/opt/make/libexec/gnubin/make /usr/local/sbin/make
    - name: Install Windows dependencies
      if: inputs.platform == 'windows'
      shell: pwsh
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        scoop install make zig
    - name: Install JavaScript deps
      shell: bash
      run: |
        corepack enable
        yarn
    - name: Run tests
      if: inputs.arch != 'aarch64' || inputs.platform != 'linux'
      shell: bash
      run: |
        make -v
        make test-ci
    - name: Run tests
      if: inputs.arch == 'aarch64' && inputs.platform == 'linux'
      shell: bash
      env:
        CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUNNER: qemu-aarch64
      run: |
        sudo apt-get install -y \
          qemu-system-arm \
          qemu-efi-aarch64 \
          qemu-utils \
          qemu-user

        make CURRENT_TARGET=aarch64-unknown-linux-musl test-ci
