#!/bin/bash
set -e

new_array=()
for value in "$@"
do
    #echo C=$value
    [[ $value != *self-contained/*crt* ]] && [[  $value != -mmacosx-version-min* ]] && new_array+=($value)
done

zig cc "${new_array[@]}"