AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  llrt-sam

  Sample SAM Template for llrt-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LlrtLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../../llrt-lambda-arm64.zip
      CompatibleRuntimes:
        - provided.al2023
      CompatibleArchitectures:
        - arm64
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: provided.al2023
      Architectures:
        - arm64
      Layers:
        - !Ref LlrtLayer
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        External:
          - "@aws-sdk"
          - "@smithy"
          - uuid
        Minify: false
        Target: "es2020"
        Sourcemap: false
        Format: esm
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - app.ts

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
