[package]
name = "llrt_abort"
description = "LLRT Module abort"
version = "0.9.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"

[lib]
name = "llrt_abort"
path = "src/lib.rs"

[features]
default = ["sleep-timers"]

sleep-timers = ["dep:llrt_scheduler"]
sleep-tokio = ["tokio"]

[dependencies]
llrt_exceptions = { version = "0.9.0-beta", path = "../llrt_exceptions" }
llrt_events = { version = "0.9.0-beta", path = "../llrt_events" }
llrt_utils = { version = "0.9.0-beta", path = "../../libs/llrt_utils", default-features = false }
rquickjs = { version = "0.14", default-features = false }

# Optional
llrt_scheduler = { version = "0.9.0-beta", path = "../../libs/llrt_scheduler", optional = true }
tokio = { version = "1", features = [
    "time",
], default-features = false, optional = true }

[dev-dependencies]
llrt_test = { path = "../../libs/llrt_test" }
tokio = { version = "1", features = ["macros", "rt", "test-util"], default-features = false }
