[package]
name = "llrt_stream_web"
description = "LLRT Module stream/web"
version = "0.4.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"

[lib]
name = "llrt_stream_web"
path = "src/lib.rs"

[dependencies]
llrt_abort = { version = "0.4.0-beta", path = "../llrt_abort" }
llrt_utils = { version = "0.4.0-beta", path = "../../libs/llrt_utils", default-features = false }
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", version = "0.8.1", default-features = false }

[dev-dependencies]
llrt_test = { path = "../../libs/llrt_test" }
tokio = { version = "1", features = ["full"] }
